# Generated by Django 5.1.4 on 2025-01-15 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_name', models.CharField(max_length=255)),
                ('motif_structure', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonosaccharideComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_num', models.IntegerField()),
                ('n_num', models.IntegerField()),
                ('f_num', models.IntegerField()),
                ('sg_num', models.IntegerField()),
                ('sn_num', models.IntegerField()),
                ('phos_num', models.IntegerField()),
                ('sulph_num', models.IntegerField()),
                ('unmod_sia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StageOfLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('journal', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('doi', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sublocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ', models.CharField(max_length=255)),
                ('structure', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModelSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.species')),
                ('stage_of_life', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DB.stageoflife')),
                ('sublocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DB.sublocation')),
            ],
        ),
        migrations.CreateModel(
            name='LastAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('affiliation', models.CharField(max_length=255)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_authors', to='DB.study')),
            ],
        ),
        migrations.CreateModel(
            name='Glycan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structural_resolution', models.TextField(blank=True, null=True)),
                ('mass', models.FloatField()),
                ('sialic_derivatization', models.BooleanField(default=False)),
                ('gu_mean', models.FloatField()),
                ('gu_max', models.FloatField()),
                ('gu_min', models.FloatField()),
                ('diagnostic_fragments', models.ManyToManyField(to='DB.diagnosticfragment')),
                ('model_species', models.ManyToManyField(to='DB.modelspecies')),
                ('monosaccharide_comp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DB.monosaccharidecomponent')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.species')),
                ('studies', models.ManyToManyField(to='DB.study')),
            ],
        ),
    ]
