# Generated by Django 5.1.4 on 2025-01-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosticfragment',
            options={'verbose_name': 'Diagnostic Fragment', 'verbose_name_plural': 'Diagnostic Fragments'},
        ),
        migrations.AlterModelOptions(
            name='glycan',
            options={'verbose_name': 'Glycan', 'verbose_name_plural': 'Glycans'},
        ),
        migrations.AlterModelOptions(
            name='lastauthor',
            options={'verbose_name': 'Last Author', 'verbose_name_plural': 'Last Authors'},
        ),
        migrations.AlterModelOptions(
            name='modelspecies',
            options={'verbose_name': 'Model Species', 'verbose_name_plural': 'Model Species'},
        ),
        migrations.AlterModelOptions(
            name='monosaccharidecomponent',
            options={'verbose_name': 'Monosaccharide Component', 'verbose_name_plural': 'Monosaccharide Components'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterModelOptions(
            name='stageoflife',
            options={'verbose_name': 'Stage of Life', 'verbose_name_plural': 'Stages of Life'},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name': 'Study', 'verbose_name_plural': 'Studies'},
        ),
        migrations.AlterModelOptions(
            name='sublocation',
            options={'verbose_name': 'Sublocation', 'verbose_name_plural': 'Sublocations'},
        ),
    ]
