# Generated by Django 5.1.5 on 2025-01-20 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0004_monosaccharidecomposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelspecies',
            name='sublocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.sublocation'),
        ),
    ]
