# Generated by Django 5.1.5 on 2025-01-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glycan',
            name='glycan_name_comp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
