# Generated by Django 5.1.5 on 2025-01-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_glycan_glycan_name_comp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monosaccharidecomponent',
            options={'verbose_name': 'Monosaccharide Composition', 'verbose_name_plural': 'Monosaccharide Compositions'},
        ),
        migrations.RemoveField(
            model_name='glycan',
            name='glycan_name_comp',
        ),
    ]
