# Generated by Django 5.1.5 on 2025-01-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0005_alter_modelspecies_sublocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glycan',
            name='id',
            field=models.CharField(editable=False, max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
