# Generated by Django 5.1.5 on 2025-01-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0006_alter_glycan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monosaccharidecomposition',
            name='composition_string',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
