# Generated by Django 6.0.6 on 2026-06-10 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0007_monosaccharidecomposition_composition_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntogenicStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, max_length=255)),
                ('age', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Ontogenic stage',
                'verbose_name_plural': 'Ontogenic stages',
            },
        ),
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ', models.CharField(blank=True, max_length=255)),
                ('structure', models.CharField(blank=True, max_length=255)),
                ('uberon_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Tissue',
                'verbose_name_plural': 'Tissues',
            },
        ),
        migrations.RemoveField(
            model_name='glycan',
            name='diagnostic_fragments',
        ),
        migrations.RemoveField(
            model_name='modelspecies',
            name='species',
        ),
        migrations.RemoveField(
            model_name='modelspecies',
            name='stage_of_life',
        ),
        migrations.RemoveField(
            model_name='modelspecies',
            name='sublocation',
        ),
        migrations.AlterModelOptions(
            name='lastauthor',
            options={'verbose_name': 'Last author', 'verbose_name_plural': 'Last authors'},
        ),
        migrations.AlterModelOptions(
            name='monosaccharidecomposition',
            options={'verbose_name': 'Monosaccharide composition', 'verbose_name_plural': 'Monosaccharide compositions'},
        ),
        migrations.RenameField(
            model_name='glycan',
            old_name='structural_resolution',
            new_name='graphical_structure',
        ),
        migrations.RenameField(
            model_name='glycan',
            old_name='sialic_derivatization',
            new_name='sialic_acid_derivatization',
        ),
        migrations.RemoveField(
            model_name='monosaccharidecomposition',
            name='A_num',
        ),
        migrations.AddField(
            model_name='glycan',
            name='brain_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='glycan',
            name='glyconnect_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='glycan',
            name='glycosmos_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='glycan',
            name='glytoucan_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='glycan',
            name='theoretical_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glycan',
            name='wurcs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modelspecies',
            name='species_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='modelspecies',
            name='species_taxid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='modelspecies',
            name='taxid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='glycan',
            name='gu_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glycan',
            name='gu_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glycan',
            name='gu_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glycan',
            name='mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glycan',
            name='model_species',
            field=models.ManyToManyField(blank=True, to='DB.modelspecies'),
        ),
        migrations.AlterField(
            model_name='glycan',
            name='monosaccharide_comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glycans', to='DB.monosaccharidecomposition'),
        ),
        migrations.AlterField(
            model_name='glycan',
            name='studies',
            field=models.ManyToManyField(blank=True, to='DB.study'),
        ),
        migrations.AlterField(
            model_name='lastauthor',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lastauthor',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='study',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='journal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='study',
            name='last_authors',
            field=models.ManyToManyField(blank=True, related_name='studies', to='DB.lastauthor'),
        ),
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='study',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelspecies',
            name='stage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DB.ontogenicstage'),
        ),
        migrations.AddField(
            model_name='modelspecies',
            name='tissue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DB.tissue'),
        ),
        migrations.DeleteModel(
            name='DiagnosticFragment',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.DeleteModel(
            name='StageOfLife',
        ),
        migrations.DeleteModel(
            name='Sublocation',
        ),
    ]
