BEGIN;
SELECT setval(pg_get_serial_sequence('"django_admin_log"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "django_admin_log";
SELECT setval(pg_get_serial_sequence('"auth_permission"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "auth_permission";
SELECT setval(pg_get_serial_sequence('"auth_group_permissions"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "auth_group_permissions";
SELECT setval(pg_get_serial_sequence('"auth_group"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "auth_group";
SELECT setval(pg_get_serial_sequence('"auth_user_groups"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "auth_user_groups";
SELECT setval(pg_get_serial_sequence('"auth_user_user_permissions"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "auth_user_user_permissions";
SELECT setval(pg_get_serial_sequence('"auth_user"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "auth_user";
SELECT setval(pg_get_serial_sequence('"django_content_type"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "django_content_type";
SELECT setval(pg_get_serial_sequence('"DB_tissue"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "DB_tissue";
SELECT setval(pg_get_serial_sequence('"DB_ontogenicstage"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "DB_ontogenicstage";
SELECT setval(pg_get_serial_sequence('"DB_modelspecies"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "DB_modelspecies";
SELECT setval(pg_get_serial_sequence('"DB_monosaccharidecomposition"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "DB_monosaccharidecomposition";
SELECT setval(pg_get_serial_sequence('"DB_lastauthor"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "DB_lastauthor";
SELECT setval(pg_get_serial_sequence('"DB_study_last_authors"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "DB_study_last_authors";
SELECT setval(pg_get_serial_sequence('"DB_study"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "DB_study";
SELECT setval(pg_get_serial_sequence('"DB_glycan_model_species"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "DB_glycan_model_species";
SELECT setval(pg_get_serial_sequence('"DB_glycan_studies"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "DB_glycan_studies";
COMMIT;
